### ISSUE TITLE
Update readme with setup instructions

### ISSUE THREAD

**Issue by risingblock** [noppefoxwolf/CIFilterCam#1]
Hi, 

Thanks for your work on replicating the WDDC video. I was trying to set this up myself and couldn't get it working. 

I've successfully installed the extension and got the app to run, however the preview image is just a black screen. 

What is required for me to get this working? I see there are a couple of comments that say "// replace..." but it's not clear what to replace these UUIDs with. 

Any help would be appreciated. 

Thank you

![CleanShot 2023-12-27 at 17 07 31](https://github.com/noppefoxwolf/CIFilterCam/assets/4132325/708b6e83-c181-4ba4-a0aa-cef5c36a10ac)

**Comment by noppefoxwolf** [comment]
I've never tried using webcam. Built-in camera also dosen't work?

**Comment by risingblock** [comment]
None of the cameras worked for me, I believe I'm missing some setup steps

Thanks for your quick reply

**Comment by noppefoxwolf** [comment]
You should to put app on /Applications and allow permission from SystemSettings privacy panel.
